import Theme from "@/providers/theme";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Theme>
        <body className="font-primary dark:bg-black bg-white min-h-screen">
          {children}
        </body>
      </Theme>
    </html>
  );
}
